src/Entity/Plats.php
<?php

namespace App\Entity;

use App\Repository\PlatsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=PlatsRepository::class)
 */
class Plats
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\ManyToOne(targetEntity=CategoriePlats::class, inversedBy="plats")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categoriePlats;

    /**
     * @ORM\ManyToOne(targetEntity=Restaurant::class, inversedBy="plats")
     * @ORM\JoinColumn(nullable=true)
     */
    private $restaurant;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive(message="Votre stock doit être positif")
     */
    private $qte;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image_file_plat;

    /**
     * @ORM\OneToMany(targetEntity=CommandePlat::class, mappedBy="plats")
     */
    private $commandePlats;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    public function __construct()
    {
        $this->commande = new ArrayCollection();
        $this->commandePlats = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCategoriePlats(): ?CategoriePlats
    {
        return $this->categoriePlats;
    }

    public function setCategoriePlats(?CategoriePlats $categoriePlats): self
    {
        $this->categoriePlats = $categoriePlats;

        return $this;
    }

    public function getRestaurant(): ?Restaurant
    {
        return $this->restaurant;
    }

    public function setRestaurant(?Restaurant $restaurant): self
    {
        $this->restaurant = $restaurant;

        return $this;
    }

    public function getQte(): ?int
    {
        return $this->qte;
    }

    public function setQte(int $qte): self
    {
        $this->qte = $qte;

        return $this;
    }

    public function getImageFilePlat(): ?string
    {
        return $this->image_file_plat;
    }

    public function setImageFilePlat(?string $image_file_plat): self
    {
        $this->image_file_plat = $image_file_plat;

        return $this;
    }

    /**
     * @return Collection|CommandePlat[]
     */
    public function getCommandePlats(): Collection
    {
        return $this->commandePlats;
    }

    public function addCommandePlat(CommandePlat $commandePlat): self
    {
        if (!$this->commandePlats->contains($commandePlat)) {
            $this->commandePlats[] = $commandePlat;
            $commandePlat->setPlats($this);
        }

        return $this;
    }

    public function removeCommandePlat(CommandePlat $commandePlat): self
    {
        if ($this->commandePlats->removeElement($commandePlat)) {
            // set the owning side to null (unless already changed)
            if ($commandePlat->getPlats() === $this) {
                $commandePlat->setPlats(null);
            }
        }

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function __call($name, $arguments)
    {
        return $this->name;
    }


}

src/Controller/PlatsController.php
<?php

namespace App\Controller;

use App\Entity\Plats;
use App\Form\Plats1Type;
use App\Repository\PlatsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

/**
 * @Route("/restaurateur/plats")
 */
class PlatsController extends AbstractController
{
    /**
     * @Route("/", name="plats_index", methods={"GET"})
     */
    public function index(PlatsRepository $platsRepository): Response
    {
        $restaurant = $this->getUser()->getRestaurant()->getId();

        return $this->render('plats/index.html.twig', [
            'plats' => $platsRepository->findBy(['restaurant' => $restaurant])
        ]);
    }

    /**
     * @Route("/new", name="plats_new", methods={"GET","POST"})
     * @param SluggerInterface $slugger
     */
    public function new(Request $request, SluggerInterface $slugger): Response
    {
        $plat = new Plats();
        $form = $this->createForm(Plats1Type::class, $plat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $imageFile = $form->get('image')->getData();

            if($imageFile)
            {
                $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$imageFile->guessExtension();
                try {
                    $imageFile->move(
                        $this->getParameter('plat_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    $newFilename = 'plat-default.jpg';
                }

                // updates the 'brochureFilename' property to store the PDF file name
                // instead of its contents
                $plat->setImageFilePlat($newFilename);
            }
            else
            {
                $plat->setImageFilePlat('plat-default.jpg');
            }

            $this->getDoctrine()->getManager()->flush();
            $entityManager = $this->getDoctrine()->getManager();
            $restaurant = $this->getUser()->getRestaurant();
            $plat->setRestaurant($restaurant);
            $entityManager->persist($plat);
            $entityManager->flush();

            return $this->redirectToRoute('plats_index');
        }

        return $this->render('plats/new.html.twig', [
            'plat' => $plat,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="plats_show", methods={"GET"})
     */
    public function show(Plats $plat): Response
    {
        return $this->render('plats/show.html.twig', [
            'plat' => $plat,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="plats_edit", methods={"GET","POST"})
     * @param SluggerInterface $slugger
     */
    public function edit(Request $request, Plats $plat, SluggerInterface $slugger): Response
    {
        $form = $this->createForm(Plats1Type::class, $plat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

        $imageFile = $form->get('image')->getData();

        if ($imageFile)
        {
            $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
            $safeFilename = $slugger->slug($originalFilename);
            $newFilename = $safeFilename . '-' . uniqid() . '.' . $imageFile->guessExtension();
            try {
                $imageFile->move(
                    $this->getParameter('plat_directory'),
                    $newFilename
                );
            } catch (FileException $e) {
                $newFilename = 'plat-default.jpg';
            }

            // updates the 'brochureFilename' property to store the PDF file name
            // instead of its contents
            $plat->setImageFilePlat($newFilename);
        }

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('plats_index');
        }

        return $this->render('plats/edit.html.twig', [
            'plat' => $plat,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="plats_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Plats $plat): Response
    {
        if ($this->isCsrfTokenValid('delete' . $plat->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($plat);
            $entityManager->flush();
        }

        return $this->redirectToRoute('plats_index');
    }

}

templates/plats/_delete_form.html.twig
<form method="post" action="{{ path('plats_delete', {'id': plat.id}) }}" onsubmit="return confirm('Êtes vous sur de vouloir supprimer cet élément?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ plat.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/plats/_form.html.twig
{{ form_start(form, {'attr':{'class':'form-group'}}) }}
<div class="d-flex justify-content-around">
    <div class="col">
        {{ form_row(form.name, {'attr':{'class':'form-control'}}) }}
    </div>
    <div class="col">
        {{ form_row(form.price, {'attr':{'class':'form-control'}}) }}
    </div>
</div>
<div class="d-flex justify-content-around">
    <div class="col">
        {{ form_row(form.qte, {'attr':{'class':'form-control'}}) }}
    </div>
    <div class="col">
        {{ form_row(form.categoriePlats, {'label':'Catégorie de plat', 'attr':{'class':'form-control'}}) }}
    </div>
</div>
<div>
    <div class="d-flex justify-content-around">
        <div class="col">
            {{ form_row(form.description, {'attr':{'class':'form-control'}}) }}
        </div>
        <div class="col">
            {{ form_row(form.image, {'attr':{'class':'form-control-file'}}) }}
        </div>
    </div>
    <div class="d-flex justify-content-center">
        <button class="btn btn-primary mt-5">{{ button_label|default('Mettre à jour') }}</button>
    </div>
    {{ form_end(form) }}

templates/plats/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification Plats{% endblock %}

{% block body %}
    <div class="offset-2 col-8">
        <h1 class="mt-4 mb-4 ml-2">Modifier les plats de votre restaurant</h1>
            {{ include('plats/_form.html.twig') }}
            <div class="d-flex justify-content-around">
            <a href="{{ path('plats_index') }}" class="btn btn-primary">Retour à la liste</a>
            {{ include('plats/_delete_form.html.twig') }}
            </div>
        </div>
{% endblock %}

templates/plats/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Voici la liste de vos plats{% endblock %}

{% block body %}

    {% if app.user.restaurant.companyName != null %}
        <div class="offset-2 col-8">
            <h1 class="text-center">Voici la liste de vos plats</h1>
            {% if plats is not empty %}

                <table class="table table-hover text-center">
                    <thead>
                    <tr>
                        <th>Image</th>
                        <th>Nom du plat</th>
                        <th>Prix</th>
                        <th>Quantité</th>
                        <th>Voir le plat</th>
                        <th>Modifier le plat</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for plat in plats %}
                        <tr>
                            <td><img src="{{ asset('img/plat/' ~ plat.imageFilePlat) }}" style="max-width: 60px"></td>
                            <td>{{ plat.name }}</td>
                            <td>{{ plat.price | format_currency('EUR') }}</td>
                            <td>{{ plat.qte }}</td>
                            <td>
                                <a href="{{ path('plats_show', {'id': plat.id}) }}" class="btn btn-info">Voir</a>
                            </td>
                            <td>
                                <a href="{{ path('plats_edit', {'id': plat.id}) }}" class="btn btn-success">Modifier</a>
                            </td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            {% else %}
                <h3 class="text-center mt-5">Aucun Plat trouvé, veuillez en ajouter</h3>
            {% endif %}

                <div class="d-flex justify-content-end mt-3">
                    <a href="{{ path('plats_new') }}" class="btn btn-primary">Ajouter un plat</a>
                </div>
        </div>
    {% else %}
        <h1 class="text-center">Veuillez finaliser votre inscription avant de gérer vos plats!</h1>
        <a href="{{ path('restaurant') }}"
           class="btn btn-primary d-flex justify-content-center ml-5 mr-5 mt-5">Retour</a>
    {% endif %}
{% endblock %}

templates/plats/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un nouveau plat{% endblock %}

{% block body %}
    <h1 class="mt-3 text-center">Ajouter un nouveau plat</h1>
    <div class="offset-2 col-8">
        {{ include('plats/_form.html.twig', {'button_label': 'Ajouter'}) }}

        <div class="d-flex justify-content-center mt-3">
            <a href="{{ path('plats_index') }}" class="btn btn-danger">Retour à la liste</a>
        </div>
    </div>
{% endblock %}

templates/plats/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{plat.name}}{% endblock %}

{% block body %}
    <div class="offset-2 col-8">

        <div class="d-flex justify-content-center mt-5">
            <div class="card" style="width: 18rem;">
                <img class='img-thumbnail'
                     src="{{ asset('img/plat/' ~ plat.imageFilePlat) }}"
                     style="max-width: 620px"
                     alt="Photo du plat">
                <div class="card-body">
                    <h5 class="card-title">{{ plat.name }}</h5>
                    <p class="card-text">{{ plat.description }}</p>

                    <div class="row">
                        <div class="col-6">Prix : {{ plat.price |format_currency('EUR') }} </div>
                        <div class="col-6">Stock : {{ plat.qte }}</div>
                    </div>
                    <div class="row mt-2">
                        <div class="col-12">Catégorie : {{ plat.categoriePlats }}</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="d-flex justify-content-around mt-5">
            <a href="{{ path('plats_index') }}" class="btn btn-primary">Retour à la liste</a>

            <a href="{{ path('plats_edit', {'id': plat.id}) }}" class="btn btn-success">Modifier le plat</a>

            {{ include('plats/_delete_form.html.twig') }}
        </div>
    </div>
{% endblock %}