src/Entity/Restaurant.php
<?php

namespace App\Entity;

use App\Repository\RestaurantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RestaurantRepository::class)
 */
class Restaurant
{
    public function __toString()
    {
        return $this->companyName;
    }

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $companyName;

    /**
     * @ORM\OneToOne(targetEntity=User::class, mappedBy="restaurant", cascade={"persist", "remove"})
     */
    private $utilisateur;

    /**
     * @ORM\ManyToMany(targetEntity=CategorieRestaurant::class, mappedBy="restaurant", cascade={"persist"})
     * @ORM\JoinTable(name="categorie_restaurant_restaurant",
     *      joinColumns={@ORM\JoinColumn(name="restaurant_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="categorie_restaurant_id", referencedColumnName="id")}
     *      )
     */
    private $categorieRestaurants;

    /**
     * @ORM\OneToMany(targetEntity=Plats::class, mappedBy="restaurant")
     */
    private $plats;

    /**
     * @ORM\OneToMany(targetEntity=Commande::class, mappedBy="restaurant")
     */
    private $commandes;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image_file_restaurant;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    public function __construct()
    {
        $this->categorieRestaurants = new ArrayCollection();
        $this->plats = new ArrayCollection();
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCompanyName(): ?string
    {
        return $this->companyName;
    }

    public function setCompanyName(string $companyName): self
    {
        $this->companyName = $companyName;

        return $this;
    }

    public function getUtilisateur(): ?User
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?User $utilisateur): self
    {
        // unset the owning side of the relation if necessary
        if ($utilisateur === null && $this->utilisateur !== null) {
            $this->utilisateur->setRestaurant(null);
        }

        // set the owning side of the relation if necessary
        if ($utilisateur !== null && $utilisateur->getRestaurant() !== $this) {
            $utilisateur->setRestaurant($this);
        }

        $this->utilisateur = $utilisateur;

        return $this;
    }

    /**
     * @return Collection|CategorieRestaurant[]
     */
    public function getCategorieRestaurants(): Collection
    {
        return $this->categorieRestaurants;
    }

    public function addCategorieRestaurant(CategorieRestaurant $categorieRestaurant): self
    {
        if (!$this->categorieRestaurants->contains($categorieRestaurant)) {
            $this->categorieRestaurants[] = $categorieRestaurant;
            $categorieRestaurant->addRestaurant($this);
        }

        return $this;
    }

    public function removeCategorieRestaurant(CategorieRestaurant $categorieRestaurant): self
    {
        if ($this->categorieRestaurants->removeElement($categorieRestaurant)) {
            $categorieRestaurant->removeRestaurant($this);
        }

        return $this;
    }

    /**
     * @return Collection|Plats[]
     */
    public function getPlats(): Collection
    {
        return $this->plats;
    }

    public function addPlat(Plats $plat): self
    {
        if (!$this->plats->contains($plat)) {
            $this->plats[] = $plat;
            $plat->setRestaurant($this);
        }

        return $this;
    }

    public function removePlat(Plats $plat): self
    {
        if ($this->plats->removeElement($plat)) {
            // set the owning side to null (unless already changed)
            if ($plat->getRestaurant() === $this) {
                $plat->setRestaurant(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Commande[]
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setRestaurant($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getRestaurant() === $this) {
                $commande->setRestaurant(null);
            }
        }

        return $this;
    }

    public function getImageFileRestaurant(): ?string
    {
        return $this->image_file_restaurant;
    }

    public function setImageFileRestaurant(?string $image_file_restaurant): self
    {
        $this->image_file_restaurant = $image_file_restaurant;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }
}

src/Entity/Ville.php
<?php

namespace App\Entity;

use App\Repository\VilleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VilleRepository::class)
 */
class Ville
{
    public function __toString()
    {
        return $this->nom_ville;
    }

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=70)
     */
    private $nom_ville;

    /**
     * @ORM\OneToMany(targetEntity=User::class, mappedBy="ville")
     */
    private $users;

    /**
     * @ORM\ManyToOne(targetEntity=Secteur::class, inversedBy="villes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Secteur;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $codePostal;

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomVille(): ?string
    {
        return $this->nom_ville;
    }

    public function setNomVille(string $nom_ville): self
    {
        $this->nom_ville = $nom_ville;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->setVille($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getVille() === $this) {
                $user->setVille(null);
            }
        }

        return $this;
    }

    public function getSecteur(): ?Secteur
    {
        return $this->Secteur;
    }

    public function setSecteur(?Secteur $Secteur): self
    {
        $this->Secteur = $Secteur;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->codePostal;
    }

    public function setCodePostal(?string $codePostal): self
    {
        $this->codePostal = $codePostal;

        return $this;
    }
}

src/Controller/AccueilClientController.php
<?php

namespace App\Controller;

use App\Entity\CategorieRestaurant;
use App\Entity\Commande;
use App\Entity\Plats;
use App\Entity\Restaurant;
use App\Form\RestaurantType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


/**
 * @Route("/client")
 */
class AccueilClientController extends AbstractController
{
    /**
     * @Route("/accueil", name="client")
     */
    public function index(): Response
    {

        $user = $this->getUser()->getAdress();
        $userId = $this->getUser()->getId();
        $idSecteur = $this->getUser()->getVille()->getSecteur()->getId();

        $commande = $this->getDoctrine()->getRepository(Commande::class);
        $commandeUser = $commande->findBy(['utilisateur'=> $userId]);

        $categorieRestaurants = $this->getDoctrine()->getRepository(CategorieRestaurant::class)
            ->findAll();

        $restaurant = $this->getDoctrine()->getRepository(Restaurant::class)->findBySecteur($idSecteur);

        return $this->render('accueil_client/index.html.twig',
            [
                'commandUser' => $commandeUser,
                'user' => $user,
                'categorieRestaurants' => $categorieRestaurants,
                'restaurants' => $restaurant,

            ]);
    }

    /**
     * @Route("/accueil/{id}", name="view_resto")
     */
    public function viewRestaurant($id): Response
    {
        $user = $this->getUser()->getAdress();
        $idSecteur = $this->getUser()->getVille()->getSecteur()->getId();

        $userId = $this->getUser()->getId();
        $commande = $this->getDoctrine()->getRepository(Commande::class);
        $commandeUser = $commande->findBy(['utilisateur'=> $userId]);

        $categorieRestaurants = $this->getDoctrine()->getRepository(CategorieRestaurant::class)
            ->findAll();

        $repo = $this->getDoctrine()->getRepository(Restaurant::class);
        $restaurant = $repo->findByCategorieAndSecteur($id, $idSecteur);

        return $this->render('accueil_client/index.html.twig',
            [
                'commandUser' => $commandeUser,
                'user' => $user,
                'categorieRestaurants' => $categorieRestaurants,
                'restaurants' => $restaurant,
            ]);
    }


    /**
     * @Route("/restaurant/{id}/menu", name="restaurant_menu")
     */
    public function viewRestaurantMenu(int $id): Response
    {
        $plats = $this->getDoctrine()->getRepository(Plats::class)->findByRestaurantAndPositifStock($id);
        return $this->render('restaurant/plat.html.twig',[
            'plats' => $plats
        ]);
    }

}

templates/accueil_client/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Bonjour, {{ app.user.firstName }} ! {% endblock %}

{% block stylesheets %}
    {{ encore_entry_link_tags('navbarLeft') }}
{% endblock %}

{% block body %}
    <div class="vertical-nav" id="sidebar">
        <ul class="nav flex-column mb-0 text-center">

            <li class="nav-item mt-3">
                <a class="nav-link font-italic" href="{{ path('client') }}">
                    Toutes catégories
                </a>
            </li>
            {% for categorieRestaurant in categorieRestaurants %}
                <li class="nav-item">
                    <a class="nav-link font-italic" href="{{ path('view_resto', {'id': categorieRestaurant.id}) }}">
                        {{ categorieRestaurant.libelle }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>

    <div class="page-content">
        {% set lastCommande = commandUser | last %}
        {% if lastCommande != "Livré" and lastCommande is not empty %}
            <div class="d-flex justify-content-center mt-3 mb-3">
                <div class="card">
                    <div class="card-body">

                        <h5 class=" card-title text-center">Votre commande ayant le numéro {{ lastCommande.id }}
                            a le statut {{ lastCommande.status }}</h5>
                    </div>
                </div>
            </div>
        {% endif %}
        <h3 class="text-center mt-3"> Votre adresse : {{ app.user.adress }} {{ app.user.ville.nomVille }}</h3>
        <div class="d-flex flex-wrap justify-content-around  mt-5">
            {% for restaurant in restaurants %}
                {% set imagePath = 'img/restaurant/' ~ restaurant.imageFileRestaurant %}

                <div class="card" style="width: 18rem;">
                    <img src="{{ asset(imagePath) }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ restaurant.companyName }}</h5>
                        <p class="card-text">{{ restaurant.description }}</p>
                        <p class="card-text">{{ restaurant.utilisateur.adress }}</p>
                        <p>{{ restaurant.utilisateur.ville.nomVille }}</p>
                        <a href="{{ path('restaurant_menu', {'id': restaurant.id}) }}" class="btn btn-primary">Voir la
                            carte</a>
                    </div>
                    <div class="card-footer text-muted">
                        <div class="d-flex justify-content-around">
                            {% for rest in restaurant.categorieRestaurants %}
                                <div>{{ rest.libelle }}</div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}