src/Entity/Ville.php
<?php

namespace App\Entity;

use App\Repository\VilleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VilleRepository::class)
 */
class Ville
{
    public function __toString()
    {
        return $this->nom_ville;
    }

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=70)
     */
    private $nom_ville;

    /**
     * @ORM\OneToMany(targetEntity=User::class, mappedBy="ville")
     */
    private $users;

    /**
     * @ORM\ManyToOne(targetEntity=Secteur::class, inversedBy="villes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Secteur;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $codePostal;

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomVille(): ?string
    {
        return $this->nom_ville;
    }

    public function setNomVille(string $nom_ville): self
    {
        $this->nom_ville = $nom_ville;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->setVille($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getVille() === $this) {
                $user->setVille(null);
            }
        }

        return $this;
    }

    public function getSecteur(): ?Secteur
    {
        return $this->Secteur;
    }

    public function setSecteur(?Secteur $Secteur): self
    {
        $this->Secteur = $Secteur;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->codePostal;
    }

    public function setCodePostal(?string $codePostal): self
    {
        $this->codePostal = $codePostal;

        return $this;
    }
}

src/Form/VilleType.php
<?php

namespace App\Form;

use App\Entity\Ville;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VilleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom_ville', TextType::class,[
                'label'=>'Nom de la ville',
                'attr'=>[
                    'placeholder'=>'Entrez le nom de la ville'
                ]
            ])
            ->add('Secteur')
            ->add('code_postal', TextType::class,[
                'label'=>'Code Postal',
                'attr'=>[
                    'placeholder'=>'Entrez le code postal de la ville'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Ville::class,
        ]);
    }
}

src/Controller/VilleController.php
<?php

namespace App\Controller;

use App\Entity\Ville;
use App\Form\VilleType;
use App\Repository\VilleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/ville")
 */
class VilleController extends AbstractController
{
    /**
     * @Route("/", name="ville_index", methods={"GET"})
     */
    public function index(VilleRepository $villeRepository): Response
    {
        return $this->render('ville/index.html.twig', [
            'villes' => $villeRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="ville_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $ville = new Ville();
        $form = $this->createForm(VilleType::class, $ville);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($ville);
            $entityManager->flush();

            return $this->redirectToRoute('ville_index');
        }

        return $this->render('ville/new.html.twig', [
            'ville' => $ville,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ville_show", methods={"GET"})
     */
    public function show(Ville $ville): Response
    {
        return $this->render('ville/show.html.twig', [
            'ville' => $ville,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="ville_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Ville $ville): Response
    {
        $form = $this->createForm(VilleType::class, $ville);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('ville_index');
        }

        return $this->render('ville/edit.html.twig', [
            'ville' => $ville,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ville_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Ville $ville): Response
    {
        if ($this->isCsrfTokenValid('delete'.$ville->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($ville);
            $entityManager->flush();
        }

        return $this->redirectToRoute('ville_index');
    }
}

templates/ville/_delete_form.html.twig
<form method="post" action="{{ path('ville_delete', {'id': ville.id}) }}" onsubmit="return confirm('Êtes vous sur de vouloir supprimer cet élément?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ville.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/ville/_form.html.twig
{{ form_start(form, {'attr':{'class':'form-group'}}) }}
<div class="d-flex justify-content-around">
    <div class="col">
        {{ form_row(form.nom_ville, {'attr':{'class':'form-control'}}) }}
    </div>
    <div class="col">
        {{ form_row(form.Secteur, {'attr':{'class':'form-control'}}) }}
    </div>
    <div class="col">
        {{ form_row(form.code_postal, {'attr':{'class':'form-control'}}) }}
    </div>
</div>
<div class="d-flex justify-content-around mt-4">
    <button class="btn btn-primary">{{ button_label|default('Mettre à jour') }}</button>
    <a href="{{ path('ville_index') }}" class="btn btn-danger">Retour à la liste</a>
</div>
{{ form_end(form) }}

templates/ville/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier la ville{% endblock %}

{% block body %}
<div class="offset-2 col-8 mt-5">
    <h1 class="text-center mb-3">Modifier la ville</h1>

    {{ include('ville/_form.html.twig') }}
{% endblock %}

templates/ville/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des villes{% endblock %}

{% block body %}
    <div class="offset-2 col-8 mt-5">
        <h1 class="text-center mt-4">Liste des villes</h1>
        {% if villes is not empty %}

            <table class="table table-hover text-center mt-4">
                <thead>
                <tr>
                    <th>Nom Ville</th>
                    <th>Secteur</th>
                    <th>Code Postal</th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for ville in villes %}
                    <tr>
                        <td>{{ ville.nomVille }}</td>
                        <td>{{ ville.Secteur.nomSecteur }}</td>
                        <td>{{ ville.codePostal }}</td>
                        <td>
                            <a href="{{ path('ville_show', {'id': ville.id}) }}" class="btn btn-info">Voir</a>
                        </td>
                        <td>
                            <a href="{{ path('ville_edit', {'id': ville.id}) }}" class="btn btn-success">Editer</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <h3 class="mt-4 text-center">Aucune ville trouvée</h3>
        {% endif %}
        <div class="d-flex justify-content-end mt-3">
            <a href="{{ path('ville_new') }}" class="btn btn-primary">Ajouter une ville</a>
        </div>
    </div>
{% endblock %}

templates/ville/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une ville{% endblock %}

{% block body %}
<div class="offset-2 col-8 mt-5">
    <h1 class="mb-3 text-center">Ajouter une ville</h1>

    {{ include('ville/_form.html.twig', {'button_label': 'Ajouter'}) }}
</div>
{% endblock %}

templates/ville/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ville{% endblock %}

{% block body %}
    <div class="offset-2 col-8 mt-5">
        <h1 class="text-center">Ville :</h1>
            <div class="d-flex justify-content-center mt-3">
                <div class="card border-danger mb-3" style="max-width: 18rem;">
                    <h4 class="card-header">{{ ville.nomVille }}</h4>
                    <div class="card-body text-danger">
                        <p class="card-text">
                       <h5>{{ ville.secteur.nomSecteur }}</h5>
                        </p>
                    </div>
                </div>
            </div>
        <div class="d-flex justify-content-around mt-4">
            <a href="{{ path('ville_index') }}" class="btn btn-primary">Retour à la liste</a>

            <a href="{{ path('ville_edit', {'id': ville.id}) }}" class="btn btn-success">Editer la ville</a>
        </div>
    </div>
{% endblock %}